### ISSUE TITLE
Trailing EOF lines are removed

### ISSUE THREAD

**Issue by mkaput** [wingyplus/json_formatter#2]
Currently, this code drops any trailing `\n` at the end of files. Personally, I would prefer to keep a single `\n` character at the end of the file, while not doing so within sigils.

I think it might be best to detect whether `contents` has trailing whitespace which includes new lines, and in such cases replace such whitespace with `"\n"`.

What do you think?

**Comment by wingyplus** [comment]
> I think it might be best to detect whether contents has trailing whitespace which includes new lines, and in such cases replace such whitespace with "\n".

Or maybe introduce a new option in `.formatter.exs` to keep the final newline if it set (maybe we should enable by default). What do you think?

**Comment by mkaput** [comment]
All depends on whether this formatter is going to be opinionated ([Prettier-style](https://github.com/prettier/prettier/issues/6360)), or configurable. I would personally go the opinionated way, so avoid configuration options as much as possible.

I think there should be a final newline when formatting files, and no final whitespace when formatting sigils ([mix format does notify you what is formatted](https://hexdocs.pm/mix/main/Mix.Tasks.Format.html#module-plugins)).

**Comment by wingyplus** [comment]
> All depends on whether this formatter is going to be opinionated (Prettier-style), or configurable. I would personally go the opinionated way, so avoid configuration options as much as possible.

I like that way too. It encourages people to use the same formatting. :)

> I think there should be a final newline when formatting files, and no final whitespace when formatting sigils (mix format does notify you what is formatted).

Agreed.

**Comment by mkaput** [comment]
Would like me to submit a patch implementing this behaviour? Or would you rather do it by yourself.

**Comment by wingyplus** [comment]
@mkaput The PR already opened. ☝️ 

Could you help me testing it? :)

**Comment by wingyplus** [comment]
@mkaput FYI. v0.2.0 is now published https://hex.pm/packages/json_formatter/0.2.0

**Comment by mkaput** [comment]
Thanks a lot! ❤️
